const ACTION_TRANSACTION_ADD = 'ACTION_TRANSACTION_ADD';
const ACTION_TRANSACTION_DELETE = 'ACTION_TRANSACTION_DELETE';

const ACTION_CATEGORY_ADD = 'ACTION_CATEGORY_ADD';
const ACTION_CATEGORY_DELETE = 'ACTION_CATEGORY_DELETE';

export {
  ACTION_TRANSACTION_ADD,
  ACTION_TRANSACTION_DELETE,
  ACTION_CATEGORY_ADD,
  ACTION_CATEGORY_DELETE
};
